syntax = "proto3";

package sistema;

// ==========================================
// MÁQUINA 4: MICROSERVICIO DE AUTENTICACIÓN
// ==========================================
service AuthService {
  rpc Login (LoginRequest) returns (LoginResponse) {}
  rpc Registro (RegistroRequest) returns (RegistroResponse) {}
}

message LoginRequest {
  string correo = 1;
  string password = 2;
}

message LoginResponse {
  bool exito = 1;
  string token = 2;
  string mensaje = 3;
}

message RegistroRequest {
  string nombre = 1;
  string correo = 2;
  string password = 3;
  string rol = 4;
  string codigo_secreto = 5;
}

message RegistroResponse {
  bool exito = 1;
  string mensaje = 2;
}

// ==========================================
// MÁQUINA 3: MICROSERVICIO DE SALAS (Lógica)
// ==========================================
service SalasService {
  rpc CrearSala (CrearSalaRequest) returns (SalaResponse) {}
  rpc UnirseSala (UnirseRequest) returns (UnirseResponse) {}
  rpc GenerarEquipos (GenerarEquiposRequest) returns (GenerarEquiposResponse) {}
  rpc ObtenerMisSalas (ObtenerSalasRequest) returns (ObtenerSalasResponse) {}
  rpc ObtenerSalasAlumno (ObtenerSalasAlumnoRequest) returns (ObtenerSalasResponse) {}
  rpc EliminarSala (EliminarSalaRequest) returns (EliminarSalaResponse) {}
  
  // ¡NUEVO!: Para consultar alumnos en tiempo real
  rpc ObtenerAlumnosSala (ObtenerAlumnosSalaRequest) returns (ObtenerAlumnosSalaResponse) {}
  
  // ¡NUEVO!: Para guardar la foto de los equipos en BD
  rpc GuardarEquipos (GuardarEquiposRequest) returns (GuardarEquiposResponse) {}

  // 👇 ¡AQUÍ VA EL CANDADO! 👇
  rpc BloquearSala (BloquearSalaRequest) returns (BloquearSalaResponse) {}
}

message CrearSalaRequest {
  int32 max_alumnos_por_equipo = 1;
  string token_docente = 2;
}

message SalaResponse {
  bool exito = 1;
  string codigo_sala = 2;
  string mensaje = 3;
}

message UnirseRequest {
  string codigo_sala = 1;
  string token_alumno = 2;
}

message UnirseResponse {
  bool exito = 1;
  string mensaje = 2;
}

message GenerarEquiposRequest {
  string codigo_sala = 1;
  string token_docente = 2;
}

message GenerarEquiposResponse {
  bool exito = 1;
  string mensaje = 2;
}

message ObtenerSalasRequest {
  string token_docente = 1;
}

message ObtenerSalasAlumnoRequest {
  string token_alumno = 1; 
}

message SalaInfo {
  string codigo_sala = 1;
  int32 max_alumnos_por_equipo = 2;
  repeated string alumnos = 3;
  string equipos_json = 4;
}

message ObtenerSalasResponse {
  bool exito = 1;
  string mensaje = 2;
  repeated SalaInfo salas = 3;
}

message EliminarSalaRequest {
  string codigo_sala = 1;
  string token_docente = 2;
}

message EliminarSalaResponse {
  bool exito = 1;
  string mensaje = 2;
}

// --- NUEVOS MENSAJES ---

message ObtenerAlumnosSalaRequest {
  string codigo_sala = 1;
}

message ObtenerAlumnosSalaResponse {
  bool exito = 1;
  repeated string alumnos = 2;
}

message GuardarEquiposRequest {
  string codigo_sala = 1;
  string token_docente = 2;
  string equipos_json = 3;
}

message GuardarEquiposResponse {
  bool exito = 1;
  string mensaje = 2;
}

message BloquearSalaRequest {
  string codigo_sala = 1;
  string token_docente = 2;
  bool estado_bloqueo = 3;
}

message BloquearSalaResponse {
  bool exito = 1;
  string mensaje = 2;
}